name: Auto Merge and Delete Branch

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  merge_and_delete:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check if branch starts with renovate/
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} == renovate/* ]]; then
            git config user.name "GitHub Actions"
            git config user.email "sg85207@gmail.com"
            git fetch origin
            git checkout main
            git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Auto-merge pull request"
            git push origin main
            git push origin --delete ${{ github.event.pull_request.head.ref }}
          else
            echo "Not a renovate/ branch, skipping auto merge."
          fi
